clean:
	-@(cd srcCosmicRay;    make clean)
	-@(cd srcEE;           make clean)
	-@(cd srcIE;           make clean)
	-@(cd srcGM;           make clean)
	-@(cd srcSC;           make clean)
	-@(cd srcUA;           make clean)

distclean:
	-@(cd srcCosmicRay;    make distclean)
	-@(cd srcEE;           make distclean)
	-@(cd srcIE;           make distclean)
	-@(cd srcGM;           make distclean)
	-@(cd srcSC;           make distclean)
	-@(cd srcUA;           make distclean)

